// ============================================================
// SafeED-UP — User Roles & Permissions Constants (Shared)
// ============================================================

const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  STATE_ADMIN: 'STATE_ADMIN',
  DISTRICT_ADMIN: 'DISTRICT_ADMIN',
  POLICE_OFFICER: 'POLICE_OFFICER',
  FIRE_OFFICER: 'FIRE_OFFICER',
  INSPECTION_OFFICER: 'INSPECTION_OFFICER',
  SCHOOL_ADMIN: 'SCHOOL_ADMIN',
  COACHING_ADMIN: 'COACHING_ADMIN',
  CITIZEN: 'CITIZEN',
};

const PERMISSIONS = {
  // User Management
  MANAGE_USERS: 'manage_users',
  VIEW_USERS: 'view_users',

  // Institution
  VIEW_ALL_INSTITUTIONS: 'view_all_institutions',
  VIEW_DISTRICT_INSTITUTIONS: 'view_district_institutions',
  VIEW_OWN_INSTITUTION: 'view_own_institution',
  CREATE_INSTITUTION: 'create_institution',
  UPDATE_INSTITUTION: 'update_institution',
  VERIFY_INSTITUTION: 'verify_institution',
  CHANGE_INSTITUTION_STATUS: 'change_institution_status',

  // Inspections
  SCHEDULE_INSPECTION: 'schedule_inspection',
  CONDUCT_INSPECTION: 'conduct_inspection',
  APPROVE_INSPECTION: 'approve_inspection',
  VIEW_INSPECTIONS: 'view_inspections',

  // Documents
  UPLOAD_DOCUMENT: 'upload_document',
  VERIFY_DOCUMENT: 'verify_document',
  DELETE_DOCUMENT: 'delete_document',

  // Compliance
  MANAGE_COMPLIANCE: 'manage_compliance',
  VIEW_COMPLIANCE: 'view_compliance',

  // Deficiencies
  CREATE_DEFICIENCY: 'create_deficiency',
  CLOSE_DEFICIENCY: 'close_deficiency',
  SUBMIT_RECTIFICATION: 'submit_rectification',
  VIEW_DEFICIENCIES: 'view_deficiencies',

  // Analytics
  VIEW_STATE_ANALYTICS: 'view_state_analytics',
  VIEW_DISTRICT_ANALYTICS: 'view_district_analytics',
  VIEW_OWN_ANALYTICS: 'view_own_analytics',

  // Reports
  GENERATE_STATE_REPORT: 'generate_state_report',
  GENERATE_DISTRICT_REPORT: 'generate_district_report',
  GENERATE_OWN_REPORT: 'generate_own_report',

  // System
  MANAGE_SYSTEM: 'manage_system',
  VIEW_AUDIT_LOGS: 'view_audit_logs',
  PUBLIC_VERIFY: 'public_verify',
};

// Role → Permission Map
const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  [ROLES.STATE_ADMIN]: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_ALL_INSTITUTIONS,
    PERMISSIONS.VERIFY_INSTITUTION,
    PERMISSIONS.CHANGE_INSTITUTION_STATUS,
    PERMISSIONS.SCHEDULE_INSPECTION,
    PERMISSIONS.APPROVE_INSPECTION,
    PERMISSIONS.VIEW_INSPECTIONS,
    PERMISSIONS.VERIFY_DOCUMENT,
    PERMISSIONS.MANAGE_COMPLIANCE,
    PERMISSIONS.VIEW_COMPLIANCE,
    PERMISSIONS.CLOSE_DEFICIENCY,
    PERMISSIONS.VIEW_DEFICIENCIES,
    PERMISSIONS.VIEW_STATE_ANALYTICS,
    PERMISSIONS.VIEW_DISTRICT_ANALYTICS,
    PERMISSIONS.GENERATE_STATE_REPORT,
    PERMISSIONS.GENERATE_DISTRICT_REPORT,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.PUBLIC_VERIFY,
  ],

  [ROLES.DISTRICT_ADMIN]: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_DISTRICT_INSTITUTIONS,
    PERMISSIONS.VERIFY_INSTITUTION,
    PERMISSIONS.CHANGE_INSTITUTION_STATUS,
    PERMISSIONS.SCHEDULE_INSPECTION,
    PERMISSIONS.APPROVE_INSPECTION,
    PERMISSIONS.VIEW_INSPECTIONS,
    PERMISSIONS.VERIFY_DOCUMENT,
    PERMISSIONS.MANAGE_COMPLIANCE,
    PERMISSIONS.VIEW_COMPLIANCE,
    PERMISSIONS.CLOSE_DEFICIENCY,
    PERMISSIONS.VIEW_DEFICIENCIES,
    PERMISSIONS.VIEW_DISTRICT_ANALYTICS,
    PERMISSIONS.GENERATE_DISTRICT_REPORT,
    PERMISSIONS.PUBLIC_VERIFY,
  ],

  [ROLES.POLICE_OFFICER]: [
    PERMISSIONS.VIEW_DISTRICT_INSTITUTIONS,
    PERMISSIONS.VIEW_INSPECTIONS,
    PERMISSIONS.VERIFY_DOCUMENT,
    PERMISSIONS.VIEW_COMPLIANCE,
    PERMISSIONS.VIEW_DEFICIENCIES,
    PERMISSIONS.VIEW_DISTRICT_ANALYTICS,
    PERMISSIONS.GENERATE_OWN_REPORT,
    PERMISSIONS.PUBLIC_VERIFY,
  ],

  [ROLES.FIRE_OFFICER]: [
    PERMISSIONS.VIEW_DISTRICT_INSTITUTIONS,
    PERMISSIONS.VIEW_INSPECTIONS,
    PERMISSIONS.VERIFY_DOCUMENT,
    PERMISSIONS.VIEW_COMPLIANCE,
    PERMISSIONS.VIEW_DEFICIENCIES,
    PERMISSIONS.VIEW_DISTRICT_ANALYTICS,
    PERMISSIONS.GENERATE_OWN_REPORT,
    PERMISSIONS.PUBLIC_VERIFY,
  ],

  [ROLES.INSPECTION_OFFICER]: [
    PERMISSIONS.VIEW_DISTRICT_INSTITUTIONS,
    PERMISSIONS.CONDUCT_INSPECTION,
    PERMISSIONS.VIEW_INSPECTIONS,
    PERMISSIONS.VERIFY_DOCUMENT,
    PERMISSIONS.MANAGE_COMPLIANCE,
    PERMISSIONS.VIEW_COMPLIANCE,
    PERMISSIONS.CREATE_DEFICIENCY,
    PERMISSIONS.CLOSE_DEFICIENCY,
    PERMISSIONS.VIEW_DEFICIENCIES,
    PERMISSIONS.GENERATE_OWN_REPORT,
    PERMISSIONS.PUBLIC_VERIFY,
  ],

  [ROLES.SCHOOL_ADMIN]: [
    PERMISSIONS.VIEW_OWN_INSTITUTION,
    PERMISSIONS.UPDATE_INSTITUTION,
    PERMISSIONS.VIEW_INSPECTIONS,
    PERMISSIONS.UPLOAD_DOCUMENT,
    PERMISSIONS.VIEW_COMPLIANCE,
    PERMISSIONS.SUBMIT_RECTIFICATION,
    PERMISSIONS.VIEW_DEFICIENCIES,
    PERMISSIONS.VIEW_OWN_ANALYTICS,
    PERMISSIONS.GENERATE_OWN_REPORT,
    PERMISSIONS.PUBLIC_VERIFY,
  ],

  [ROLES.COACHING_ADMIN]: [
    PERMISSIONS.VIEW_OWN_INSTITUTION,
    PERMISSIONS.UPDATE_INSTITUTION,
    PERMISSIONS.VIEW_INSPECTIONS,
    PERMISSIONS.UPLOAD_DOCUMENT,
    PERMISSIONS.VIEW_COMPLIANCE,
    PERMISSIONS.SUBMIT_RECTIFICATION,
    PERMISSIONS.VIEW_DEFICIENCIES,
    PERMISSIONS.VIEW_OWN_ANALYTICS,
    PERMISSIONS.GENERATE_OWN_REPORT,
    PERMISSIONS.PUBLIC_VERIFY,
  ],

  [ROLES.CITIZEN]: [
    PERMISSIONS.PUBLIC_VERIFY,
  ],
};

module.exports = { ROLES, PERMISSIONS, ROLE_PERMISSIONS };
